spring.application.name=runpod-worker
server.servlet.context-path=/worker/api

# Database Configuration
spring.datasource.url=jdbc:postgresql://111.111.111:5432/runpodworker
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true  ? dinonaktifkan, gunakan logging.level.org.hibernate.SQL saja
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Jackson Configuration
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.deserialization.accept-empty-string-as-null-object=true

# Runpod API Configuration
runpod.api-token=token
runpod.run.path.async=/run
runpod.run.path.sync=/runsync
runpod.worker.rembg.url=https://api.runpod.ai/v2/endpointId/run
runpod.worker.upscaler.url=https://api.runpod.ai/v2/endpointId/run

# Redis Configuration
spring.data.redis.host=111.111.111
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=5000ms
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1

# Redis Pub/Sub Channel Names
redis.channel.job-upscaler-request=job-upscaler-request
redis.channel.job-upscaler-response=job-upscaler-response

redis.channel.job-rembg-request=job-rembg-request
redis.channel.job-rembg-response=job-rembg-response